name: Auto Build and Release

on:
    push:
        branches:
            - main
        paths:
            - "release/diaphantium.user.js"

permissions:
    contents: write

jobs:
    build-and-release:
        runs-on: ubuntu-latest

        steps:
            - name: Checkout repository
              uses: actions/checkout@v4

            - name: Extract version from diaphantium.user.js
              id: extract_version
              run: |
                  version=$(grep -oP '@version\s+\K[\w.+-]+' release/diaphantium.user.js)
                  echo "VERSION=$version" >> $GITHUB_ENV
                  echo "version=$version" >> $GITHUB_OUTPUT

            - name: Check if version is stable (SemVer)
              id: check_stable
              run: |
                  # Official SemVer regex from semver.org
                  semver_regex='^(0|[1-9]\d*)\.(0|[1-9]\d*)\.(0|[1-9]\d*)$'
                  
                  if [[ "$VERSION" =~ $semver_regex ]]; then
                    echo "is_stable=true" >> $GITHUB_OUTPUT
                    echo "✅ Version $VERSION is stable (matches SemVer)"
                  else
                    echo "is_stable=false" >> $GITHUB_OUTPUT
                    echo "ℹ️ Version $VERSION is not stable (dev/alpha/beta/rc)"
                  fi

            - name: Set up Node.js
              uses: actions/setup-node@v4
              with:
                  node-version: "20"

            - name: Install dependencies
              run: npm ci

            - name: Build artifacts
              run: |
                  # Create temporary directory for artifacts
                  mkdir -p /tmp/build-artifacts
                  
                  # Build diaphantium.min.js with webpack to temporary location
                  npx webpack --mode production --output-path /tmp/build-artifacts
                  echo "✅ Built diaphantium.min.js"

            - name: Prepare commit info
              id: prepare_commit
              run: |
                  # Get commit info from main branch (before switching)
                  COMMIT_HASH=$(git rev-parse HEAD)
                  COMMIT_DATE=$(git log -1 --format=%ad --date=short)
                  echo "COMMIT_HASH=$COMMIT_HASH" >> $GITHUB_ENV
                  echo "COMMIT_DATE=$COMMIT_DATE" >> $GITHUB_ENV
                  
                  echo "✅ Prepared commit info from main branch"

            - name: Push to builds branch
              run: |
                  git config user.name "github-actions[bot]"
                  git config user.email "github-actions[bot]@users.noreply.github.com"
                  
                  # Clean working directory before switching branches
                  # Remove node_modules and other build artifacts to prevent them from being committed
                  rm -rf node_modules
                  git clean -fd -e /tmp
                  echo "✅ Cleaned working directory"
                  
                  # Switch to builds branch or create it
                  git fetch origin builds 2>/dev/null || true
                  if git ls-remote --heads origin builds | grep -q builds; then
                    git checkout builds
                  else
                    git checkout --orphan builds
                    git rm -rf . 2>/dev/null || true
                  fi
                  
                  # Create versions directory ONLY in builds branch
                  mkdir -p "versions/$VERSION"
                  
                  # Copy built files from temporary location
                  cp /tmp/build-artifacts/diaphantium.min.js "versions/$VERSION/"
                  echo "✅ Copied built files to versions/$VERSION"
                  
                  # Update stable.json if this is a stable version
                  if [ "${{ steps.check_stable.outputs.is_stable }}" == "true" ]; then
                    # Create stable.json if it doesn't exist
                    if [ ! -f stable.json ]; then
                      echo '{"versions":[]}' > stable.json
                    fi
                    
                    # Check if this version already exists in stable.json
                    if ! grep -q "\"version\": \"$VERSION\"" stable.json 2>/dev/null; then
                      # Add new stable version using jq
                      jq --arg version "$VERSION" \
                         --arg date "$COMMIT_DATE" \
                         --arg hash "$COMMIT_HASH" \
                         --arg link "https://cdn.jsdelivr.net/gh/OrakomoRi/Diaphantium@$COMMIT_HASH/release/diaphantium.user.js" \
                         '.versions += [{"version": $version, "date": $date, "hash": $hash, "link": $link}]' \
                         stable.json > stable_tmp.json
                      mv stable_tmp.json stable.json
                      
                      echo "✅ Added version $VERSION to stable.json"
                    else
                      echo "ℹ️ Version $VERSION already exists in stable.json"
                    fi
                  fi
                  
                  # Create vercel.json for deployment configuration
                  cat > vercel.json << 'EOF'
                  {
                    "version": 2,
                    "public": true,
                    "headers": [
                      {
                        "source": "stable.json",
                        "headers": [
                          {
                            "key": "Cache-Control",
                            "value": "public, max-age=0, must-revalidate"
                          },
                          {
                            "key": "Access-Control-Allow-Origin",
                            "value": "*"
                          }
                        ]
                      },
                      {
                        "source": "versions/(.*)",
                        "headers": [
                          {
                            "key": "Cache-Control",
                            "value": "public, max-age=300, must-revalidate"
                          },
                          {
                            "key": "Access-Control-Allow-Origin",
                            "value": "*"
                          }
                        ]
                      }
                    ]
                  }
                  EOF
                  echo "✅ Created vercel.json"
                  
                  # Add all changes
                  git add -A
                  
                  # Create commit message
                  if [ "${{ steps.check_stable.outputs.is_stable }}" == "true" ]; then
                    echo -e "$VERSION\n\nbuild: release artifacts (stable)" > commit-msg.txt
                  else
                    echo -e "$VERSION\n\nbuild: release artifacts" > commit-msg.txt
                  fi
                  
                  git commit -F commit-msg.txt || echo "No changes to commit"
                  git push origin builds

            - name: Create GitHub release (only for stable versions)
              if: steps.check_stable.outputs.is_stable == 'true'
              uses: softprops/action-gh-release@v2
              with:
                  tag_name: ${{ env.VERSION }}
                  name: ${{ env.VERSION }}
                  body: |
                      ## Diaphantium ${{ env.VERSION }}
                      
                      Stable release built automatically.
                      
                      **Download:**
                      - [diaphantium.user.js](https://raw.githubusercontent.com/OrakomoRi/Diaphantium/main/release/diaphantium.user.js)
                      - [diaphantium.min.js](https://cdn.jsdelivr.net/gh/OrakomoRi/Diaphantium@builds/versions/${{ env.VERSION }}/diaphantium.min.js)
                  files: |
                      versions/${{ env.VERSION }}/diaphantium.min.js
              env:
                  GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
